apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    name: postgres-service
    app: auth-app
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    name: postgres-pod
    app: auth-app
